//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2020-05-15 오후 1:43:30
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace PeiuPlatform.Hubbub
{

    /// <summary>
    /// VIEW
    /// </summary>
    public partial class VwCurrentcommand
    {

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
            VwCurrentcommand toCompare = obj as VwCurrentcommand;
            if (toCompare == null)
            {
                return false;
            }

            if (!Object.Equals(this.Date, toCompare.Date))
                return false;
            if (!Object.Equals(this.Hour, toCompare.Hour))
                return false;
            if (!Object.Equals(this.Minute, toCompare.Minute))
                return false;

            return true;
        }

        public override int GetHashCode()
        {
            int hashCode = 13;
            hashCode = (hashCode * 7) + Date.GetHashCode();
            hashCode = (hashCode * 7) + Hour.GetHashCode();
            hashCode = (hashCode * 7) + Minute.GetHashCode();
            return hashCode;
        }

        #endregion
        /// <summary>
        /// There are no comments for VwCurrentcommand constructor in the schema.
        /// </summary>
        public VwCurrentcommand()
        {
            OnCreated();
        }


        /// <summary>
        /// There are no comments for Date in the schema.
        /// </summary>
        public virtual System.DateTime Date
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Hour in the schema.
        /// </summary>
        public virtual int Hour
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Minute in the schema.
        /// </summary>
        public virtual int Minute
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Ess1 in the schema.
        /// </summary>
        public virtual float Ess1
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Ess2 in the schema.
        /// </summary>
        public virtual float Ess2
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Ess3 in the schema.
        /// </summary>
        public virtual float Ess3
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Ess4 in the schema.
        /// </summary>
        public virtual float Ess4
        {
            get;
            set;
        }
    }

}
