//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2020-10-26 오후 4:53:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Hubbub
{

    /// <summary>
    /// VIEW
    /// </summary>
    public partial class VwDigitalOutputPoint {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          VwDigitalOutputPoint toCompare = obj as VwDigitalOutputPoint;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Hubbubid, toCompare.Hubbubid))
            return false;
          if (!Object.Equals(this.Deviceindex, toCompare.Deviceindex))
            return false;
          if (!Object.Equals(this.Functioncode, toCompare.Functioncode))
            return false;
          if (!Object.Equals(this.Offset, toCompare.Offset))
            return false;
          if (!Object.Equals(this.Commandcode, toCompare.Commandcode))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Hubbubid.GetHashCode();
          hashCode = (hashCode * 7) + Deviceindex.GetHashCode();
          hashCode = (hashCode * 7) + Functioncode.GetHashCode();
          hashCode = (hashCode * 7) + Offset.GetHashCode();
          hashCode = (hashCode * 7) + Commandcode.GetHashCode();
          return hashCode;
        }
        
        #endregion
        /// <summary>
        /// There are no comments for VwDigitalOutputPoint constructor in the schema.
        /// </summary>
        public VwDigitalOutputPoint()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Hubbubid in the schema.
        /// </summary>
        public virtual int Hubbubid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Deviceindex in the schema.
        /// </summary>
        public virtual int Deviceindex
        {
            get;
            set;
        }

    
        /// <summary>
        /// 3  : Holding Register
        /// </summary>
        public virtual int Functioncode
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Offset in the schema.
        /// </summary>
        public virtual int Offset
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Commandcode in the schema.
        /// </summary>
        public virtual int Commandcode
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Commandorder in the schema.
        /// </summary>
        public virtual short Commandorder
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Commandname in the schema.
        /// </summary>
        public virtual string Commandname
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Commanddesc in the schema.
        /// </summary>
        public virtual string Commanddesc
        {
            get;
            set;
        }

    
        /// <summary>
        /// value * scale
        /// </summary>
        public virtual short? Outputvalue
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Datatypeid in the schema.
        /// </summary>
        public virtual int Datatypeid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Datatypename in the schema.
        /// </summary>
        public virtual string Datatypename
        {
            get;
            set;
        }

    
        /// <summary>
        /// 1 : PCS\n2 : BMS\n3 : PV
        /// </summary>
        public virtual int Devicetypeid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Devicetype in the schema.
        /// </summary>
        public virtual string Devicetype
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Disable in the schema.
        /// </summary>
        public virtual bool Disable
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        public virtual string Description
        {
            get;
            set;
        }

    
        /// <summary>
        /// value / scalefactor
        /// </summary>
        public virtual float Scalefactor
        {
            get;
            set;
        }
    }

}
