//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2020-10-26 오후 4:53:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Hubbub
{

    /// <summary>
    /// There are no comments for Hubbub.ModbusDigitalStatusPoint, HubhubSharedLib in the schema.
    /// </summary>
    public partial class ModbusDigitalStatusPoint {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          ModbusDigitalStatusPoint toCompare = obj as ModbusDigitalStatusPoint;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Hubbubid, toCompare.Hubbubid))
            return false;
          if (!Object.Equals(this.Deviceindex, toCompare.Deviceindex))
            return false;
          if (!Object.Equals(this.Pcsstatusid, toCompare.Pcsstatusid))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Hubbubid.GetHashCode();
          hashCode = (hashCode * 7) + Deviceindex.GetHashCode();
          hashCode = (hashCode * 7) + Pcsstatusid.GetHashCode();
          return hashCode;
        }
        
        #endregion
        /// <summary>
        /// There are no comments for ModbusDigitalStatusPoint constructor in the schema.
        /// </summary>
        public ModbusDigitalStatusPoint()
        {
            this.Functioncode = 3;
            this.Match = 1;
            this.Bitflag = 0;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Hubbubid in the schema.
        /// </summary>
        public virtual int Hubbubid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Deviceindex in the schema.
        /// </summary>
        public virtual int Deviceindex
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pcsstatusid in the schema.
        /// </summary>
        public virtual int Pcsstatusid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Functioncode in the schema.
        /// </summary>
        public virtual int Functioncode
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Offset in the schema.
        /// </summary>
        public virtual int Offset
        {
            get;
            set;
        }

    
        /// <summary>
        /// ?? ?? ??? TRUE ? ???? FALSE? ????
        /// </summary>
        public virtual sbyte Match
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Bitflag in the schema.
        /// </summary>
        public virtual int Bitflag
        {
            get;
            set;
        }
    }

}
