//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2020-08-10 오전 10:53:32
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Hubbub
{

    /// <summary>
    /// There are no comments for Hubbub.ModbusConnectionInfo, HubhubSharedLib in the schema.
    /// </summary>
    public partial class ModbusConnectionInfo {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for ModbusConnectionInfo constructor in the schema.
        /// </summary>
        public ModbusConnectionInfo()
        {
            this.Host = @"127.0.0.1";
            this.Port = 502;
            this.Protocolid = 1000;
            this.Baudrate = 9600;
            this.Databits = 8;
            this.Parity = @"None";
            this.Stopbits = @"One";
            this.Slaveid = 1;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// TCP : 127.0.0.1
        /// RTU : COM1
        /// </summary>
        public virtual string Host
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Port in the schema.
        /// </summary>
        public virtual int? Port
        {
            get;
            set;
        }

    
        /// <summary>
        /// 1000	Modbus tcp slave
        /// 1001	DNP3
        /// 1002	Mqtt
        /// 1003	Twincat ADS
        /// 1004	Modbus rtu slave
        /// </summary>
        public virtual int Protocolid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Baudrate in the schema.
        /// </summary>
        public virtual int Baudrate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Databits in the schema.
        /// </summary>
        public virtual int Databits
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Parity in the schema.
        /// </summary>
        public virtual string Parity
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Stopbits in the schema.
        /// </summary>
        public virtual string Stopbits
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Slaveid in the schema.
        /// </summary>
        public virtual int Slaveid
        {
            get;
            set;
        }
    }

}
