//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2020-10-26 오후 4:53:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Hubbub
{

    /// <summary>
    /// There are no comments for Hubbub.DataType, HubhubSharedLib in the schema.
    /// </summary>
    public partial class DataType {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for DataType constructor in the schema.
        /// </summary>
        public DataType()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        public virtual string Description
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Sizebyword in the schema.
        /// </summary>
        public virtual short Sizebyword
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Isunsigned in the schema.
        /// </summary>
        public virtual bool Isunsigned
        {
            get;
            set;
        }
    }

}
