//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2020-10-26 오후 4:53:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Hubbub
{

    /// <summary>
    /// VIEW
    /// </summary>
    public partial class VwModbusInputPoint {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          VwModbusInputPoint toCompare = obj as VwModbusInputPoint;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Hubbubid, toCompare.Hubbubid))
            return false;
          if (!Object.Equals(this.Deviceindex, toCompare.Deviceindex))
            return false;
          if (!Object.Equals(this.Functioncode, toCompare.Functioncode))
            return false;
          if (!Object.Equals(this.Pointtypeid, toCompare.Pointtypeid))
            return false;
          if (!Object.Equals(this.Offset, toCompare.Offset))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Hubbubid.GetHashCode();
          hashCode = (hashCode * 7) + Deviceindex.GetHashCode();
          hashCode = (hashCode * 7) + Functioncode.GetHashCode();
          hashCode = (hashCode * 7) + Pointtypeid.GetHashCode();
          hashCode = (hashCode * 7) + Offset.GetHashCode();
          return hashCode;
        }
        
        #endregion
        /// <summary>
        /// There are no comments for VwModbusInputPoint constructor in the schema.
        /// </summary>
        public VwModbusInputPoint()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Hubbubid in the schema.
        /// </summary>
        public virtual int Hubbubid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Deviceindex in the schema.
        /// </summary>
        public virtual int Deviceindex
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Functioncode in the schema.
        /// </summary>
        public virtual int Functioncode
        {
            get;
            set;
        }

    
        /// <summary>
        /// 0 : AI
        /// 1 : DI
        /// 2 : ST
        /// </summary>
        public virtual int Pointtypeid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Offset in the schema.
        /// </summary>
        public virtual int Offset
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Aigroupid in the schema.
        /// </summary>
        public virtual int Aigroupid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Deviceid in the schema.
        /// </summary>
        public virtual long? Deviceid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Datatypeid in the schema.
        /// </summary>
        public virtual int Datatypeid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Sizebyword in the schema.
        /// </summary>
        public virtual short Sizebyword
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Scalefactor in the schema.
        /// </summary>
        public virtual float Scalefactor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Byteindex in the schema.
        /// </summary>
        public virtual int Byteindex
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Disable in the schema.
        /// </summary>
        public virtual bool Disable
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Defaultvalue in the schema.
        /// </summary>
        public virtual float Defaultvalue
        {
            get;
            set;
        }
    }

}
