//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2020-10-26 오후 4:53:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Hubbub
{

    /// <summary>
    /// VIEW
    /// </summary>
    public partial class VwStandardAnalogPoint {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for VwStandardAnalogPoint constructor in the schema.
        /// </summary>
        public VwStandardAnalogPoint()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Typeid in the schema.
        /// </summary>
        public virtual int Typeid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fieldname in the schema.
        /// </summary>
        public virtual string Fieldname
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Deviceid in the schema.
        /// </summary>
        public virtual int Deviceid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Disable in the schema.
        /// </summary>
        public virtual sbyte Disable
        {
            get;
            set;
        }
    }

}
